# Generated by Django 6.0.2 on 2026-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de contacto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
    ]
