# Generated by Django 6.0.2 on 2026-02-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_alter_contract_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('cif', models.CharField(max_length=20, verbose_name='CIF')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('COORDINATOR', 'COORDINATOR')], default='COORDINATOR', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='companies',
            field=models.ManyToManyField(related_name='projects', to='api.company'),
        ),
    ]
