# Generated by Django 6.0.2 on 2026-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_alter_user_role_alter_companycontact_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
    ]
