# Generated by Django 6.0.2 on 2026-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_cif_alter_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcenter',
            name='risk_info_file',
        ),
        migrations.AddField(
            model_name='workcenter',
            name='risk_info_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL/Base64 de Riesgos'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='url',
            field=models.TextField(verbose_name='URL/Base64 del documento'),
        ),
    ]
