# Generated by Django 6.0.2 on 2026-02-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_workcenter_risk_info_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workcenter'),
        ),
    ]
