# Generated by Django 6.0.2 on 2026-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_work_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='notification_contacts',
            field=models.ManyToManyField(blank=True, related_name='meeting_notifications', to='api.companycontact'),
        ),
    ]
