# Generated by Django 6.0.2 on 2026-02-26 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meeting_notification_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
