# Generated by Django 6.0.2 on 2026-02-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_meeting_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
