# Generated by Django 6.0.2 on 2026-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_meeting_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='document_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
