# Generated by Django 6.0.2 on 2026-02-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_meeting_document_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_data', models.TextField(verbose_name='Base64 Document Data')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.meeting')),
            ],
            options={
                'verbose_name': 'Documento de Reunión',
                'verbose_name_plural': 'Documentos de Reunión',
            },
        ),
    ]
