# Generated by Django 6.0.2 on 2026-03-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_meetingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contract_managers', to='api.companycontact'),
        ),
    ]
