# Generated by Django 6.0.2 on 2026-03-02 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_project_contract_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('type', models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('ONLINE', 'ONLINE')], max_length=20, verbose_name='Tipo')),
                ('teams_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PROGRAMADA', 'PROGRAMADA'), ('EN_CURSO', 'EN_CURSO'), ('REALIZADA', 'REALIZADA'), ('CANCELADA', 'CANCELADA')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('provinces', models.JSONField(blank=True, default=list, verbose_name='Provincias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='follow_up_meetings', to='api.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_meetings', to='api.contract')),
                ('work_centers', models.ManyToManyField(blank=True, related_name='follow_up_meetings', to='api.workcenter')),
            ],
            options={
                'verbose_name': 'Reunión de Seguimiento',
                'verbose_name_plural': 'Reuniones de Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='FollowUpMeetingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reunion', models.IntegerField(default=1, verbose_name='Número de Reunión')),
                ('revision_informacion', models.TextField(blank=True, null=True, verbose_name='Revisión de la información suministrada')),
                ('observaciones_intercambio', models.TextField(blank=True, null=True, verbose_name='Observaciones al intercambio de información')),
                ('solapes_empresas', models.TextField(blank=True, null=True, verbose_name='Existencia de solapes entre empresas')),
                ('accidentes_trabajo', models.TextField(blank=True, null=True, verbose_name='Accidentes de trabajo')),
                ('emergencia', models.TextField(blank=True, null=True, verbose_name='Emergencia')),
                ('otros_temas', models.TextField(blank=True, null=True, verbose_name='Otros temas')),
                ('ruegos_preguntas', models.TextField(blank=True, null=True, verbose_name='Ruegos y preguntas')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='api.followupmeeting')),
            ],
            options={
                'verbose_name': 'Configuración de Acta de Seguimiento',
                'verbose_name_plural': 'Configuraciones de Acta de Seguimiento',
            },
        ),
    ]
