# Generated by Django 6.0.2 on 2026-03-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_followupmeeting_followupmeetingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupmeeting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar'),
        ),
    ]
