# Generated by Django 6.0.2 on 2026-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_followupmeeting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupmeeting',
            name='document_data',
            field=models.TextField(blank=True, null=True, verbose_name='Acta generada (Base64)'),
        ),
        migrations.AddField(
            model_name='followupmeeting',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followupmeeting',
            name='notification_contacts',
            field=models.ManyToManyField(blank=True, related_name='followup_notifications', to='api.companycontact'),
        ),
    ]
