# Generated by Django 6.0.2 on 2026-03-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_followupmeeting_document_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupmeetingconfig',
            name='signatures',
            field=models.JSONField(blank=True, default=list, verbose_name='Firmas'),
        ),
    ]
